<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U5U852D" failures="1" tests="6" name="Personal Loan" time="0.022" errors="0" timestamp="16 Nov 2021 11:33:45 GMT">
  <testcase classname="test.Day1" name="Demo" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.Day1.Demo(Day1.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Day1" name="Demo2" time="0.001"/>
  <testcase classname="test.Day2" name="p2loan" time="0.002"/>
  <testcase classname="test.Day2" name="ploan" time="0.0"/>
  <testcase classname="test.Day4" name="MobLoginHomeLoan" time="0.001"/>
  <testcase classname="test.Day4" name="WebLoginHomeLoan" time="0.0"/>
</testsuite> <!-- Personal Loan -->
